### ISSUE TITLE
writing todo's

### ISSUE THREAD

**Issue by judithfan** [cogtoolslab/graphical_conventions_latex#3]
### Judy
- [ ] computational reproducibility checks: dataframe generation + analyses
    - [ ] Make sure that dataframe generation + feature extraction run clean for both v1.0 and v2.0
output 
    - [ ] 1 group dataframe CSV with expID as a new column to distinguish 1.0 from 2.0
    - [ ] vgg19 fc6 feature matrices (+metadata CSV) for 1.0 and 2.0
    - [ ] write draft of README for dataframe generation & analysis files
- [ ] Diagnosticity analysis logic figure

### Robert
- [ ] Write up diagnosticity analysis results 
- [ ] Make diagnosticity results figures
- [ ] Include supplemental section reporting replication of other sections on v2.0
    - [ ] Performance-based analyses
    - [ ] Feature-based analyses
    - [ ] Control experiments

### Writing
- [ ] Writing: expand introduction?
- [ ] Make diagnosticity schematic (with maps) and results figure?

### 
- [ ] NHB checklist
- [ ] cover letter
- [ ] check in about co-authorship
